### ISSUE TITLE
waiting code

### ISSUE THREAD

**Issue by oylz** [whlzy/FiT#1]

**Comment by yuedajiong** [comment]
me too

**Comment by QingSongZ** [comment]
me too！

**Comment by Godk02** [comment]
Still not open

**Comment by WZDTHU** [comment]
Thanks for your interest on our work, all the sample codes have been released. Our FiTv2 paper has been released at https://arxiv.org/pdf/2410.13925. The checkpoints are in https://huggingface.co/InfImagine/FiT and https://huggingface.co/InfImagine/FiTv2.
