### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by Zhou2019** [whlzy/FiT#5]
Congratulations on your paper being accepted by ICML. When will the code be released?

**Comment by WZDTHU** [comment]
Thanks for your interest on our work, all the sample codes have been released. Our FiTv2 paper has been released at https://arxiv.org/pdf/2410.13925. The checkpoints are in https://huggingface.co/InfImagine/FiT and https://huggingface.co/InfImagine/FiTv2.
